Markup:
  icon: "icon-code"
  pages:
    markup/templating: "Templating"
    "https://twig.symfony.com/doc/3.x/": "Twig Docs@"

Variables:
  icon: "icon-subscript"
  itemClass: "code-item"
  pages:
    markup/this-page: "this.page"
    markup/this-layout: "this.layout"
    markup/this-theme: "this.theme"
    markup/this-param: "this.param"
    markup/this-controller: "this.controller"
    markup/this-environment: "this.environment"
    markup/this-session: "this.session"

Tags:
  icon: "icon-tags"
  itemClass: "code-item"
  pages:
    markup/tag-page: "{% page %}"
    markup/tag-partial: "{% partial %}"
    markup/tag-content: "{% content %}"
    markup/tag-component: "{% component %}"
    markup/tag-placeholder: "{% placeholder %}"
    markup/tag-scripts: "{% scripts %}"
    markup/tag-styles: "{% styles %}"
    markup/tag-flash: "{% flash %}"
    markup/tag-verbatim: "{% verbatim %}"
    markup/tag-macro: "{% macro %}"
    markup/tag-for: "{% for %}"
    markup/tag-if: "{% if %}"

Filters:
  icon: "icon-quote-right"
  itemClass: "code-item"
  pages:
    markup/filter-app: "| app"
    markup/filter-asset: "| asset"
    markup/filter-default: "| default"
    markup/filter-image-width: "| imageWidth"
    markup/filter-image-height: "| imageHeight"
    markup/filter-md: "| md[_line|_safe]"
    markup/filter-media: "| media"
    markup/filter-page: "| page"
    markup/filter-raw: "| raw"
    markup/filter-resize: "| resize"
    markup/filter-theme: "| theme"
    markup/filter-trans: "| trans"

Functions:
  icon: "icon-eraser"
  itemClass: "code-item"
  pages:
    markup/function-str: "str_*()"
    markup/function-form: "form_*()"
    markup/function-html: "html()"
    markup/function-dump: "dump()"
