name: Docs

on:
    push:
        branches:
            - develop
            - 1.2
            - 1.1
            - 1.0
    pull_request:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Lint files
              uses: avto-dev/markdown-lint@v1
              with:
                args: './**/*.md'
